version: '3.6'

services: 
    app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 3000:3000
        volumes:
          - .:/app
          - "/app/node_modules"
        depends_on:
          - db

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: fabien
            MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080